name: Continuous Integration Pipeline

on:
  push:
    branches:
      - main
      - feature/*

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['7.0.x']
    services:
      dynamodb-unit-test:
        image: amazon/dynamodb-local
        ports:
          - 8001:8000
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3.0.3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Install Dependencies
        working-directory: ./API/App
        run: dotnet restore
      - name: Build
        working-directory: ./API/App
        run: dotnet build --configuration Release --no-restore
      - name: API Unit Tests
        working-directory: ./API/Test/Unit
        run: dotnet test
      - name: Setup DynamoDB
        working-directory: ./DAL/Local
        run: dotnet run 8001
      - name: DynamoDB DAL Unit Tests
        working-directory: ./DAL/Test
        run:  dotnet test
